// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbvylpytntjujbsydbdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFidnlscHl0bnRqdWpic3lkYmRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMzM0OTksImV4cCI6MjA2ODYwOTQ5OX0.HSflVmnIYFJ9OaDYDIhnHqiFRHsh5Gp8BQkvWkU00ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});